
desc 'lib tag:0.0.1 tgt:target or add s1:source s2:source 使用这个航道, 可以快速的对自己的私有库, 进行升级维护'
lane :lib do |options|

	tagName = options[:tag]
	targetName = options[:tg]
	sourceName1 = options[:s1]
	sourceName2 = options[:s2] 
	sources = []
	sources << sourceName1
	sources << sourceName2

	# 具体这个巷道上面执行哪些行为
	# 1. pod install
	cocoapods(
		clean: true,
		podfile: "./Example/Podfile"
	)

	# 2. git add .
	git_add(path: ".")
	#    git commit -m 'xxx'
	git_commit(path: ".", message: "版本升级维护: #{tagName}")
	#    git push origin master
	push_to_git_remote

	# 验证tag是否存在,如果存在, 应该删除本地标签和远程标签
	if git_tag_exists(tag: tagName)
	    UI.message("发现tag:#{tagName} 已经存在, 执行删除动作.")
	    remove_tag(tag:tagName)
	end


	# 3. git tag 标签名称
	add_git_tag(
		tag: tagName
	)
	#    git push --tags
	push_git_tags

	# 4. pod spec lint
	# 私有库验证失败时把这个验证注释掉
	if sources
		pod_lib_lint(sources: sources,allow_warnings: true)
	else
		pod_lib_lint(allow_warnings: true)
	end

	#  pod repo push XXXX xxx.podspec
	if sources
		pod_push(path: "#{targetName}.podspec", repo: "alonemonkey", sources: sources, allow_warnings: true)
	else
		pod_push(path: "#{targetName}.podspec", repo: "alonemonkey", allow_warnings: true)
	end

end
